name: Build and Release

on:
  push:
    tags:
      - 'v*'  # Triggers on tags starting with 'v', e.g., v1.0.0

permissions:
  contents: write-all

jobs:
  build-linux:
    name: Build Linux Executable
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller

      - name: Build Executable
        run: |
          pyinstaller --onefile --name dicomtag dicomtag/main.py
          mkdir -p dist/linux
          mv dist/dicomtag dist/linux/

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: linux-executable
          path: dist/linux/

  build-windows:
    name: Build Windows Executable
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller

      - name: Build Executable
        run: |
          pyinstaller --onefile --name dicomtag.exe --noconsole dicomtag/main.py
          mkdir -p dist/windows
          mv dist/dicomtag.exe dist/windows/

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: windows-executable
          path: dist/windows/

  release:
    name: Create GitHub Release
    needs: [build-linux, build-windows]  # Wait for both build jobs to finish
    runs-on: ubuntu-latest

    steps:
      - name: Download Linux Artifacts
        uses: actions/download-artifact@v4
        with:
          name: linux-executable
          path: ./dist/linux

      - name: Download Windows Artifacts
        uses: actions/download-artifact@v4
        with:
          name: windows-executable
          path: ./dist/windows

      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false

      - name: Upload Linux Binary
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dist/linux/dicomtag  # Linux binary
          asset_name: dicomtag-linux
          asset_content_type: application/octet-stream

      - name: Upload Windows Binary
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dist/windows/dicomtag.exe  # Windows binary
          asset_name: dicomtag-windows.exe
          asset_content_type: application/octet-stream
