name: Build and Release

on:
  push:
    tags:
      - "v*.*.*"  # Trigger on version tags like v1.0.0

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller

      - name: Build executable
        run: |
          pyinstaller --onefile --name "dicomtag-${{ matrix.os }}" dicomtag/main.py

      - name: Archive executable
        uses: actions/upload-artifact@v3
        with:
          name: dicomtag-${{ matrix.os }}
          path: dist/dicomtag-${{ matrix.os }}

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: dicomtag-${{ matrix.os }}

      - name: Publish release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
